In [4]:
'''
Note: Tobi added the following code block on 1/26/2022 to update how to access 
the required data frame for this analysis. I commented out the original data access method,
shown below in cell 2.
'''

#import required libraries
import os
import pandas as pd
import numpy as np

#find the current directory
current_directory = os.getcwd()

#moves up one folder in the file directory (in order to get to the input folder)
path_parent = os.path.dirname(current_directory)

'''
Note about the data:
The folder name for the original data files is "Input", which contains the following files:
1. PSC_data_trimmed.csv: data file containing just the subset of 50 variables
2. Main.csv = the original, ~ 2 million dollar entry dataset 
3. Columns.csv = a datafile containing the subset of columns from the original dataset that we want to use
'''
#joins the file path together and reads in the data frame

df = pd.read_csv(os.path.join(path_parent, "Data",  "PSC_data_trimmed.csv"))


C:\Users\lakna\AppData\Roaming\Python\Python38\site-packages\IPython\core\interactiveshell.py:3251: DtypeWarning: Columns (8,20,40,41,43,44,45,46,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
#import pandas as pd
#df = pd.read_csv ('PSC_data_trimmed.csv')


: 

In [4]:
df.head()

Unnamed: 0  JPR_ID OFF_SEX OFF_RACE     dofage        otn  OFN_TITLE  \
0           1  640001       F    White  36.689938  H182628-5         18   
1           2  642480       M    White  18.540726          0         75   
2           3  660434       M    White  36.914442   H3618344         75   
3           4  628940       M    Black  22.297057   G0816126         18   
4           5  594048       M    White  40.087611  H240127-6         75   

  OFN_COUNT                                       OFN_LABEL OFN_GRADE  ...  \
0         1  Corruption of Minors - when of a sexual nature       M-1  ...   
1         1                                       DUI - M-2       M-2  ...   
2         1                                       DUI - M-2       M-2  ...   
3         1                                  Simple Assault       M-2  ...   
4         1                                       DUI - M-1       M-1  ...   

   id_variable  PCS_OFF_ID conform OFF_CRIMEFREE SGR_LVL_OGS_PRS DOB2  \
0      1904581         NaN     NaN           NaN             NaN  NaN   
1      1157226         NaN     NaN           NaN             NaN  NaN   
2      1467650         NaN     NaN           NaN             NaN  NaN   
3      1746031         NaN     NaN           NaN             NaN  NaN   
4      1374131         NaN     NaN           NaN             NaN  NaN   

  MS_OFFBODY  MS_SENTJP  JP_CC_BUG ofn_label  
0        NaN        NaN        NaN       NaN  
1        NaN        NaN        NaN       NaN  
2        NaN        NaN        NaN       NaN  
3        NaN        NaN        NaN       NaN  
4        NaN        NaN        NaN       NaN  

[5 rows x 48 columns]

In [5]:
df.size

124494528

In [6]:
dfc = df.copy()

In [318]:
dfc.head()['INC_END']

0          NaN
1    02 Dec 02
2    27 Apr 01
3          NaN
4    01 Jan 03
Name: INC_END, dtype: object

In [319]:
df['OFF_SEX'].unique()

array(['F', 'M', 'U'], dtype=object)

In [320]:
dfU = df[df['OFF_SEX']=='U']

In [321]:
dfU.head()

Unnamed: 0  JPR_ID OFF_SEX OFF_RACE     dofage        otn  OFN_TITLE  \
18          19  665877       U    Black  23.561944  M910065-2         35   
19          20  665877       U    Black  25.864476          0         35   
31          32  596175       U  Unknown  23.219713  H109123-0         18   
54          55  660950       U  Unknown  27.526352  H224606-4         18   
55          56  660950       U  Unknown  27.534565  H224603-1         18   

   OFN_COUNT                                        OFN_LABEL OFN_GRADE  ...  \
18         1  Possession With Intent to Deliver: Drug Unknown         F  ...   
19         1  Possession With Intent to Deliver: Drug Unknown         F  ...   
31         3                 Theft - Deception; $200 - $2,000       M-1  ...   
54         1                                  Forgery - Other       M-1  ...   
55         1                                  Forgery - Other       M-1  ...   

    id_variable  PCS_OFF_ID conform OFF_CRIMEFREE SGR_LVL_OGS_PRS DOB2  \
18      1640630         NaN     NaN           NaN             NaN  NaN   
19      1640630         NaN     NaN           NaN             NaN  NaN   
31      1516869         NaN     NaN           NaN             NaN  NaN   
54      1371759         NaN     NaN           NaN             NaN  NaN   
55      1371759         NaN     NaN           NaN             NaN  NaN   

   MS_OFFBODY  MS_SENTJP  JP_CC_BUG ofn_label  
18        NaN        NaN        NaN       NaN  
19        NaN        NaN        NaN       NaN  
31        NaN        NaN        NaN       NaN  
54        NaN        NaN        NaN       NaN  
55        NaN        NaN        NaN       NaN  

[5 rows x 48 columns]

In [322]:
df["OFF_SEX"].replace({"F": 0, "M": 1, "U":2}, inplace=True)

In [323]:
df[df['OFF_SEX'].isnull()==True]

Empty DataFrame
Columns: [Unnamed: 0, JPR_ID, OFF_SEX, OFF_RACE, dofage, otn, OFN_TITLE, OFN_COUNT, OFN_LABEL, OFN_GRADE, grade, ogs, prs, GUIDELINE_RANGE, SGR_LVL, INC_SANCTION_EXISTS, INC_TYPE, incmin, incmax, INC_RELATIONSHIP, INC_RELATEDTO, INC_RELATEDOTN, STATE_IP, IP_SANCTION_EXISTS, PROB_SANCTION_EXISTS, county, JPO_ID, glepoch, sip, MS_SANCTION, dof, dos, INC_END, INC_START, IP_END, IP_START, dob, OFF_AGE, id_variable, PCS_OFF_ID, conform, OFF_CRIMEFREE, SGR_LVL_OGS_PRS, DOB2, MS_OFFBODY, MS_SENTJP, JP_CC_BUG, ofn_label]
Index: []

[0 rows x 48 columns]

In [324]:
df[df['OFF_RACE'].isnull()==True]

Empty DataFrame
Columns: [Unnamed: 0, JPR_ID, OFF_SEX, OFF_RACE, dofage, otn, OFN_TITLE, OFN_COUNT, OFN_LABEL, OFN_GRADE, grade, ogs, prs, GUIDELINE_RANGE, SGR_LVL, INC_SANCTION_EXISTS, INC_TYPE, incmin, incmax, INC_RELATIONSHIP, INC_RELATEDTO, INC_RELATEDOTN, STATE_IP, IP_SANCTION_EXISTS, PROB_SANCTION_EXISTS, county, JPO_ID, glepoch, sip, MS_SANCTION, dof, dos, INC_END, INC_START, IP_END, IP_START, dob, OFF_AGE, id_variable, PCS_OFF_ID, conform, OFF_CRIMEFREE, SGR_LVL_OGS_PRS, DOB2, MS_OFFBODY, MS_SENTJP, JP_CC_BUG, ofn_label]
Index: []

[0 rows x 48 columns]

In [325]:
df['OFF_RACE'].unique()

array(['White', 'Black', 'Unknown', 'Other', 'Hispanic',
       'American Indian', 'Asian/Pacific Island'], dtype=object)

In [326]:
df["OFF_RACE"].replace({'Unknown': 0,'White': 1, 'Black':2,'American Indian': 3,'Asian/Pacific Island': 4,'Hispanic':5, 'Other':6}, inplace=True)



In [327]:
df['OFN_GRADE'].unique()

array(['M-1', 'M-2', 'F', 'F-3', 'F-2', 'M-3', 'M', 'F-1', 'H-2', 'H-1'],
      dtype=object)

In [328]:
df[df['OFN_GRADE'].isnull()==True]

Empty DataFrame
Columns: [Unnamed: 0, JPR_ID, OFF_SEX, OFF_RACE, dofage, otn, OFN_TITLE, OFN_COUNT, OFN_LABEL, OFN_GRADE, grade, ogs, prs, GUIDELINE_RANGE, SGR_LVL, INC_SANCTION_EXISTS, INC_TYPE, incmin, incmax, INC_RELATIONSHIP, INC_RELATEDTO, INC_RELATEDOTN, STATE_IP, IP_SANCTION_EXISTS, PROB_SANCTION_EXISTS, county, JPO_ID, glepoch, sip, MS_SANCTION, dof, dos, INC_END, INC_START, IP_END, IP_START, dob, OFF_AGE, id_variable, PCS_OFF_ID, conform, OFF_CRIMEFREE, SGR_LVL_OGS_PRS, DOB2, MS_OFFBODY, MS_SENTJP, JP_CC_BUG, ofn_label]
Index: []

[0 rows x 48 columns]

In [329]:
#df["OFN_GRADE"].replace({'F': 0,'F-1': 1, 'F-2':2,'F-2':3,'H-1': 4,'H-2': 5,'M': 6, 'M-1':7, 'M-2':8, 'M-3':9}, inplace=True)








In [330]:
df.head()

Unnamed: 0  JPR_ID  OFF_SEX  OFF_RACE     dofage        otn  OFN_TITLE  \
0           1  640001        0         1  36.689938  H182628-5         18   
1           2  642480        1         1  18.540726          0         75   
2           3  660434        1         1  36.914442   H3618344         75   
3           4  628940        1         2  22.297057   G0816126         18   
4           5  594048        1         1  40.087611  H240127-6         75   

  OFN_COUNT                                       OFN_LABEL OFN_GRADE  ...  \
0         1  Corruption of Minors - when of a sexual nature       M-1  ...   
1         1                                       DUI - M-2       M-2  ...   
2         1                                       DUI - M-2       M-2  ...   
3         1                                  Simple Assault       M-2  ...   
4         1                                       DUI - M-1       M-1  ...   

   id_variable  PCS_OFF_ID conform OFF_CRIMEFREE SGR_LVL_OGS_PRS DOB2  \
0      1904581         NaN     NaN           NaN             NaN  NaN   
1      1157226         NaN     NaN           NaN             NaN  NaN   
2      1467650         NaN     NaN           NaN             NaN  NaN   
3      1746031         NaN     NaN           NaN             NaN  NaN   
4      1374131         NaN     NaN           NaN             NaN  NaN   

  MS_OFFBODY  MS_SENTJP  JP_CC_BUG ofn_label  
0        NaN        NaN        NaN       NaN  
1        NaN        NaN        NaN       NaN  
2        NaN        NaN        NaN       NaN  
3        NaN        NaN        NaN       NaN  
4        NaN        NaN        NaN       NaN  

[5 rows x 48 columns]

In [331]:
df.columns

Index(['Unnamed: 0', 'JPR_ID', 'OFF_SEX', 'OFF_RACE', 'dofage', 'otn',
       'OFN_TITLE', 'OFN_COUNT', 'OFN_LABEL', 'OFN_GRADE', 'grade', 'ogs',
       'prs', 'GUIDELINE_RANGE', 'SGR_LVL', 'INC_SANCTION_EXISTS', 'INC_TYPE',
       'incmin', 'incmax', 'INC_RELATIONSHIP', 'INC_RELATEDTO',
       'INC_RELATEDOTN', 'STATE_IP', 'IP_SANCTION_EXISTS',
       'PROB_SANCTION_EXISTS', 'county', 'JPO_ID', 'glepoch', 'sip',
       'MS_SANCTION', 'dof', 'dos', 'INC_END', 'INC_START', 'IP_END',
       'IP_START', 'dob', 'OFF_AGE', 'id_variable', 'PCS_OFF_ID', 'conform',
       'OFF_CRIMEFREE', 'SGR_LVL_OGS_PRS', 'DOB2', 'MS_OFFBODY', 'MS_SENTJP',
       'JP_CC_BUG', 'ofn_label'],
      dtype='object')

In [332]:
df[df['grade'].isnull()==True]

Empty DataFrame
Columns: [Unnamed: 0, JPR_ID, OFF_SEX, OFF_RACE, dofage, otn, OFN_TITLE, OFN_COUNT, OFN_LABEL, OFN_GRADE, grade, ogs, prs, GUIDELINE_RANGE, SGR_LVL, INC_SANCTION_EXISTS, INC_TYPE, incmin, incmax, INC_RELATIONSHIP, INC_RELATEDTO, INC_RELATEDOTN, STATE_IP, IP_SANCTION_EXISTS, PROB_SANCTION_EXISTS, county, JPO_ID, glepoch, sip, MS_SANCTION, dof, dos, INC_END, INC_START, IP_END, IP_START, dob, OFF_AGE, id_variable, PCS_OFF_ID, conform, OFF_CRIMEFREE, SGR_LVL_OGS_PRS, DOB2, MS_OFFBODY, MS_SENTJP, JP_CC_BUG, ofn_label]
Index: []

[0 rows x 48 columns]

In [333]:
df['grade'].unique()

array([ 4,  3,  5,  6,  7,  2,  1,  8,  9, 10])

In [334]:
df['SGR_LVL'].unique()

array(['2', '1', '3', '4', '-', '5', '~', nan], dtype=object)

In [335]:
#df["SGR_LVL"].replace({'nan':''}, inplace=True)



In [336]:
df['SGR_LVL'].unique()

array(['2', '1', '3', '4', '-', '5', '~', nan], dtype=object)

In [337]:
df['SGR_LVL'] = df['SGR_LVL'].fillna('')

In [338]:
df['SGR_LVL'].replace({'-': '', '~':''}, inplace=True)

In [339]:
df['SGR_LVL'].unique()

array(['2', '1', '3', '4', '', '5'], dtype=object)

In [340]:
df['INC_TYPE'].unique()

array([nan, 'County Facility', 'Unknown', 'State Facility'], dtype=object)

In [341]:
df["INC_TYPE"].replace({'Unknown': 0,'County Facility': 1, 'State Facility':2}, inplace=True)

In [342]:
df['INC_TYPE'].unique()

array([nan,  1.,  0.,  2.])

In [343]:
df['incmin'].unique()

array([           nan, 6.57894737e-02, 6.00000000e+00, ...,
       9.64934211e+01, 1.52302632e+01, 5.63157895e+00])

In [344]:
df['incmax'].unique()

array([        nan, 12.        ,  0.06578947, ..., 15.85526316,
       16.44736842, 55.59210526])

In [345]:
df['INC_RELATIONSHIP'].unique()

array([nan, 'Consecutive', 'Concurrent', 'X'], dtype=object)

In [346]:
df['INC_RELATIONSHIP'].replace({'Consecutive':0,'Concurrent':1, 'X':2}, inplace=True)

In [347]:
df['INC_RELATIONSHIP'].unique()

array([nan,  0.,  1.,  2.])

In [348]:
df['STATE_IP'].unique()

array(['N', 'Y'], dtype=object)

In [349]:
df['STATE_IP'].replace({'N': 0,'Y': 1}, inplace=True)

In [350]:
df['IP_SANCTION_EXISTS'].unique()

array(['N', 'Y', nan], dtype=object)

In [351]:
df['IP_SANCTION_EXISTS'].replace({'N': 0,'Y': 1}, inplace=True)

In [352]:
df['PROB_SANCTION_EXISTS'].unique()


array(['Y', 'N', nan], dtype=object)

In [353]:
df['PROB_SANCTION_EXISTS'].replace({'N': 0,'Y': 1}, inplace=True)

In [354]:
df['county'].unique()

array(['Cambria', 'Chester', 'Bucks', 'Allegheny', 'Clarion',
       'Westmoreland', 'Lehigh', 'Philadelphia', 'Delaware', 'Montgomery',
       'Crawford', 'Washington', 'Cumberland', 'Franklin', 'Lackawanna',
       'Erie', 'Berks', 'Dauphin', 'York', 'Fayette', 'Lancaster',
       'Luzerne', 'Schuylkill', 'Mercer', 'Beaver', 'Armstrong',
       'Venango', 'Monroe', 'Lebanon', 'Carbon', 'Northampton',
       'Northumberland', 'Bradford', 'Union', 'Mifflin', 'Wyoming',
       'Centre', 'Susquehanna', 'Lawrence', 'Greene', 'Blair', 'Juniata',
       'Lycoming', 'Adams', 'Columbia', 'Butler', 'McKean', 'Forest',
       'Snyder', 'Indiana', 'Clearfield', 'Perry', 'Wayne', 'Huntingdon',
       'Tioga', 'Somerset', 'Clinton', 'Elk', 'Warren', 'Pike', 'Fulton',
       'Montour', 'Potter', 'Bedford', 'Sullivan', 'Jefferson', 'Cameron',
       'PCCD'], dtype=object)

In [355]:
df['INC_SANCTION_EXISTS'].unique()

array(['N', 'Y', nan], dtype=object)

In [356]:
df['INC_SANCTION_EXISTS'].replace({'N': 0,'Y': 1}, inplace=True)

In [357]:
df['county'].replace({'Cambria': 11, 'Chester': 15, 'Bucks':9, 'Allegheny': 2, 'Clarion' :16,
       'Westmoreland':65, 'Lehigh':39, 'Philadelphia':51, 'Delaware':23, 'Montgomery':46,
       'Crawford':20, 'Washington':63, 'Cumberland':21, 'Franklin':28, 'Lackawanna':35,
       'Erie':25, 'Berks':6, 'Dauphin':22, 'York':67, 'Fayette':26, 'Lancaster':36,
       'Luzerne':40, 'Schuylkill':54, 'Mercer':43, 'Beaver':4, 'Armstrong':3,
       'Venango':61, 'Monroe':45, 'Lebanon':38, 'Carbon':13, 'Northampton':48,
       'Northumberland':49, 'Bradford':8, 'Union':60, 'Mifflin':44, 'Wyoming':66,
       'Centre':14, 'Susquehanna':58, 'Lawrence':37, 'Greene':30, 'Blair':7, 'Juniata':34,
       'Lycoming':41, 'Adams':1, 'Columbia':19, 'Butler':10, 'McKean':42, 'Forest':27,
       'Snyder':55, 'Indiana':32, 'Clearfield':17, 'Perry':50, 'Wayne':64, 'Huntingdon':31,
       'Tioga':59, 'Somerset':56, 'Clinton':18, 'Elk':24, 'Warren':62, 'Pike':52, 'Fulton':29,
       'Montour':47, 'Potter':53, 'Bedford':5, 'Sullivan': 57, 'Jefferson':33, 'Cameron':12,
       'PCCD':0}, inplace=True)

In [358]:
df['county'].unique()

array([11, 15,  9,  2, 16, 65, 39, 51, 23, 46, 20, 63, 21, 28, 35, 25,  6,
       22, 67, 26, 36, 40, 54, 43,  4,  3, 61, 45, 38, 13, 48, 49,  8, 60,
       44, 66, 14, 58, 37, 30,  7, 34, 41,  1, 19, 10, 42, 27, 55, 32, 17,
       50, 64, 31, 59, 56, 18, 24, 62, 52, 29, 47, 53,  5, 57, 33, 12,  0])

In [359]:
df['MS_SANCTION'].unique()

array([ 5.,  3.,  4.,  6.,  1., nan,  2.])

In [360]:
df.describe()

Unnamed: 0        JPR_ID       OFF_SEX      OFF_RACE        dofage  \
count  2.593636e+06  2.593636e+06  2.593636e+06  2.593636e+06  2.589731e+06   
mean   1.296818e+06  3.694824e+06  7.993030e-01  1.383833e+00  3.210911e+01   
std    7.487184e+05  2.126428e+06  4.020448e-01  8.339339e-01  1.354135e+01   
min    1.000000e+00  1.722000e+03  0.000000e+00  0.000000e+00 -6.871795e+03   
25%    6.484098e+05  1.568437e+06  1.000000e+00  1.000000e+00  2.297878e+01   
50%    1.296818e+06  4.921428e+06  1.000000e+00  1.000000e+00  2.953593e+01   
75%    1.945227e+06  5.465322e+06  1.000000e+00  2.000000e+00  3.932101e+01   
max    2.593636e+06  6.134361e+06  2.000000e+00  6.000000e+00  3.623929e+02   

          OFN_TITLE         grade           ogs  INC_SANCTION_EXISTS  \
count  2.593636e+06  2.593636e+06  2.592947e+06         2.525638e+06   
mean   3.262362e+01  3.658754e+00  3.500368e+00         4.465149e-01   
std    2.147387e+01  2.074664e+00  2.450546e+00         4.971312e-01   
min    3.000000e+00  1.000000e+00  0.000000e+00         0.000000e+00   
25%    1.800000e+01  2.000000e+00  2.000000e+00         0.000000e+00   
50%    1.800000e+01  4.000000e+00  3.000000e+00         0.000000e+00   
75%    3.500000e+01  5.000000e+00  5.000000e+00         1.000000e+00   
max    7.700000e+01  1.000000e+01  1.500000e+01         1.000000e+00   

           INC_TYPE  ...  IP_SANCTION_EXISTS  PROB_SANCTION_EXISTS  \
count  1.127735e+06  ...        2.525638e+06          2.525638e+06   
mean   1.343246e+00  ...        8.890031e-02          5.031054e-01   
std    4.770848e-01  ...        2.845999e-01          4.999905e-01   
min    0.000000e+00  ...        0.000000e+00          0.000000e+00   
25%    1.000000e+00  ...        0.000000e+00          0.000000e+00   
50%    1.000000e+00  ...        0.000000e+00          1.000000e+00   
75%    2.000000e+00  ...        0.000000e+00          1.000000e+00   
max    2.000000e+00  ...        1.000000e+00          1.000000e+00   

             county        JPO_ID      sip   MS_SANCTION        OFF_AGE  \
count  2.593636e+06  2.593636e+06  10841.0  2.593625e+06  800943.000000   
mean   3.010923e+01  5.726500e+06      1.0  3.835421e+00      31.078002   
std    2.070458e+01  3.341527e+06      0.0  1.544131e+00      26.301981   
min    0.000000e+00  2.365000e+03      1.0  1.000000e+00   -7828.000000   
25%    1.000000e+01  2.448761e+06      1.0  3.000000e+00      22.000000   
50%    2.600000e+01  7.397284e+06      1.0  4.000000e+00      28.000000   
75%    4.800000e+01  8.510823e+06      1.0  5.000000e+00      39.000000   
max    6.700000e+01  9.935539e+06      1.0  6.000000e+00    1874.000000   

        id_variable    PCS_OFF_ID  SGR_LVL_OGS_PRS  
count  2.593636e+06  1.694336e+06     1.689697e+06  
mean   1.458400e+06  4.258689e+05     2.347637e+00  
std    2.639681e+05  2.432659e+05     1.069654e+00  
min    1.000001e+06  2.000000e+00     1.000000e+00  
25%    1.230525e+06  2.307875e+05     2.000000e+00  
50%    1.459135e+06  3.988690e+05     2.000000e+00  
75%    1.685714e+06  6.712732e+05     3.000000e+00  
max    1.916197e+06  8.793060e+05     5.000000e+00  

[8 rows x 24 columns]

In [361]:
df.dtypes

Unnamed: 0                int64
JPR_ID                    int64
OFF_SEX                   int64
OFF_RACE                  int64
dofage                  float64
otn                      object
OFN_TITLE                 int64
OFN_COUNT                object
OFN_LABEL                object
OFN_GRADE                object
grade                     int64
ogs                     float64
prs                      object
GUIDELINE_RANGE          object
SGR_LVL                  object
INC_SANCTION_EXISTS     float64
INC_TYPE                float64
incmin                  float64
incmax                  float64
INC_RELATIONSHIP        float64
INC_RELATEDTO            object
INC_RELATEDOTN           object
STATE_IP                  int64
IP_SANCTION_EXISTS      float64
PROB_SANCTION_EXISTS    float64
county                    int64
JPO_ID                    int64
glepoch                  object
sip                     float64
MS_SANCTION             float64
dof                      object
dos     

In [362]:
df['INC_END'] = pd.to_datetime(df['INC_END'])

In [363]:
df['INC_START'] = pd.to_datetime(df['INC_START'])

In [364]:
df['IP_END'] = pd.to_datetime(df['IP_END'])

In [365]:
df['IP_START'] = pd.to_datetime(df['IP_START'])

In [382]:
df['dob'] = pd.to_datetime(df['dob'])

In [367]:
df['dos'] = pd.to_datetime(df['dos'])

In [368]:
df['dof'] = pd.to_datetime(df['dof'])

In [369]:
df['INC_END_DAYS'] = (df['INC_END'].sub(pd.to_datetime('01/01/1900'))).dt.days

In [370]:
df['INC_START_DAYS'] = df['INC_START'].sub(pd.to_datetime('01/01/1900')).dt.days

In [371]:
df['IP_END_DAYS'] = df['IP_END'].sub(pd.to_datetime('01/01/1900')).dt.days

In [372]:
df['IP_START_DAYS'] = df['IP_START'].sub(pd.to_datetime('01/01/1900')).dt.days

In [373]:
df['DOB_DAYS'] = df['dob'].sub(pd.to_datetime('01/01/1900')).dt.days

In [374]:
df['DOS_DAYS'] = df['dos'].sub(pd.to_datetime('01/01/1900')).dt.days

In [375]:
df['DOF_DAYS'] = df['dof'].sub(pd.to_datetime('01/01/1900')).dt.days

In [376]:
#df['dob'][df['dob'].isnull() & df['DOB2'].notnull()]
df.dob.fillna(df.DOB2, inplace=True)


In [377]:
df.head()

Unnamed: 0  JPR_ID  OFF_SEX  OFF_RACE     dofage        otn  OFN_TITLE  \
0           1  640001        0         1  36.689938  H182628-5         18   
1           2  642480        1         1  18.540726          0         75   
2           3  660434        1         1  36.914442   H3618344         75   
3           4  628940        1         2  22.297057   G0816126         18   
4           5  594048        1         1  40.087611  H240127-6         75   

  OFN_COUNT                                       OFN_LABEL OFN_GRADE  ...  \
0         1  Corruption of Minors - when of a sexual nature       M-1  ...   
1         1                                       DUI - M-2       M-2  ...   
2         1                                       DUI - M-2       M-2  ...   
3         1                                  Simple Assault       M-2  ...   
4         1                                       DUI - M-1       M-1  ...   

   MS_SENTJP  JP_CC_BUG ofn_label INC_END_DAYS INC_START_DAYS  IP_END_DAYS  \
0        NaN        NaN       NaN          NaN            NaN          NaN   
1        NaN        NaN       NaN      37590.0        37226.0          NaN   
2        NaN        NaN       NaN      37006.0        37005.0          NaN   
3        NaN        NaN       NaN          NaN            NaN          NaN   
4        NaN        NaN       NaN      37620.0        36892.0          NaN   

   IP_START_DAYS  DOB_DAYS  DOS_DAYS  DOF_DAYS  
0            NaN   59739.0     37052   36615.0  
1            NaN   29751.0     37226   36523.0  
2            NaN   59923.0     37005   36881.0  
3            NaN   28557.0     37031   36701.0  
4            NaN   58695.0     36892   36812.0  

[5 rows x 55 columns]

In [378]:
df['OFFENSE_YEAR'] = df['dof'].dt.year

In [379]:
df['SANCTION_YEAR'] = df['dos'].dt.year

In [383]:
df['BIRTH_YEAR'] = df['dob'].dt.year

In [384]:
cols = list(df.columns.values)

In [385]:
cols = list(df.columns.values)

In [386]:
cols

['Unnamed: 0',
 'JPR_ID',
 'OFF_SEX',
 'OFF_RACE',
 'dofage',
 'otn',
 'OFN_TITLE',
 'OFN_COUNT',
 'OFN_LABEL',
 'OFN_GRADE',
 'grade',
 'ogs',
 'prs',
 'GUIDELINE_RANGE',
 'SGR_LVL',
 'INC_SANCTION_EXISTS',
 'INC_TYPE',
 'incmin',
 'incmax',
 'INC_RELATIONSHIP',
 'INC_RELATEDTO',
 'INC_RELATEDOTN',
 'STATE_IP',
 'IP_SANCTION_EXISTS',
 'PROB_SANCTION_EXISTS',
 'county',
 'JPO_ID',
 'glepoch',
 'sip',
 'MS_SANCTION',
 'dof',
 'dos',
 'INC_END',
 'INC_START',
 'IP_END',
 'IP_START',
 'dob',
 'OFF_AGE',
 'id_variable',
 'PCS_OFF_ID',
 'conform',
 'OFF_CRIMEFREE',
 'SGR_LVL_OGS_PRS',
 'DOB2',
 'MS_OFFBODY',
 'MS_SENTJP',
 'JP_CC_BUG',
 'ofn_label',
 'INC_END_DAYS',
 'INC_START_DAYS',
 'IP_END_DAYS',
 'IP_START_DAYS',
 'DOB_DAYS',
 'DOS_DAYS',
 'DOF_DAYS',
 'OFFENSE_YEAR',
 'SANCTION_YEAR',
 'BIRTH_YEAR']

In [387]:
df = df[[
 'JPR_ID',
 'OFF_SEX',
 'OFF_RACE',
 'dofage',
 'otn',
 'OFN_TITLE',
 'OFN_COUNT',
 'OFN_LABEL',
 'OFN_GRADE',
 'grade',
 'ogs',
 'prs',
 'GUIDELINE_RANGE',
 'SGR_LVL',
 'INC_SANCTION_EXISTS',
 'INC_TYPE',
 'incmin',
 'incmax',
 'INC_RELATIONSHIP',
 'INC_RELATEDTO',
 'INC_RELATEDOTN',
 'STATE_IP',
 'IP_SANCTION_EXISTS',
 'PROB_SANCTION_EXISTS',
 'county',
 'JPO_ID',
 'glepoch',
 'sip',
 'MS_SANCTION',
 'dof',
'DOF_DAYS',
 'OFFENSE_YEAR',
 'dos',
          'DOS_DAYS',
 'SANCTION_YEAR',
 'INC_END',
          'INC_END_DAYS',
          'INC_START_DAYS',
 'INC_START',
 'IP_END',
     'IP_END_DAYS',
 'IP_START',
    

 'IP_START_DAYS',
 'dob',
'DOB_DAYS', 'BIRTH_YEAR',
 'OFF_AGE',
 'id_variable',
 'PCS_OFF_ID',
 'conform',
 'OFF_CRIMEFREE',
 'SGR_LVL_OGS_PRS',
 'DOB2',
 'MS_OFFBODY',
 'MS_SENTJP',
 'JP_CC_BUG',
 'ofn_label'
 ]]

In [388]:
df.to_csv('cleaned.csv')